minVersion: '0.13.2'
github:
  owner: getsentry
  repo: sentry-xamarin
changelogPolicy: auto
statusProvider:
  name: github
artifactProvider:
  name: github
targets:
  - name: nuget
  - name: github
  - name: registry
    type: sdk
    config:
      canonical: "nuget:Sentry.Xamarin"
  - name: registry
    type: sdk
    config:
      canonical: "nuget:Sentry.Xamarin.Forms"
